version: '3'

services:

  front-end:
    build: front-end/
    container_name: cruddy-front
    ports:
      - '80:3000'

  server:
    build: server/
    container_name: cruddy-server
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@cruddy:5432/cruddy

  database:
    image: postgres:latest
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cruddy
    volumes:
      - ./db:/var/lib/postgresql/data